import { Inventory } from '../inventory.entity';
import { Listing } from '../../listing/listing.entity';
import {
  Entity,
  Column,
  PrimaryGeneratedColumn,
  OneToMany,
  JoinColumn,
  ManyToOne,
} from 'typeorm';
import { Tag } from './tag/tag.entity';
import { Model } from './model/model.entity';

@Entity()
export class InventoryItem {
  @PrimaryGeneratedColumn()
  id: number;

  @Column({ nullable: false }) // TODO: set foreign key on part
  part: number;
    
  @JoinColumn()
  @ManyToOne(() => Model, model => model.inventoryItems)
  model: Model;

  @Column({ nullable: false }) // TODO: set foreign key on model
  model: number;

  @JoinColumn()
  @ManyToOne(() => Inventory, (inventory) => inventory.items)
  inventory: Inventory;

  @Column({ default: 0 })
  quantity: number;

  @Column({ default: 0 })
  publicCount: number;

  @Column({ type: 'varchar', length: 4000 })
  notes: string;

  @Column({ type: 'varchar', length: 4000 })
  attributes: string;

  @OneToMany(() => Listing, (listing) => listing.inventoryItem)
  listings: Listing[];

  @ManyToMany(() => Tag, tag => tag.inventoryItems)
  @JoinTable() // autogenerated name: "inventory_item_tags_tag"
  tags: Tag[];
}
