import { Inventory } from '../inventory/inventory.entity';
import { Listing } from '../listing/listing.entity';
import {
  Entity,
  Column,
  PrimaryGeneratedColumn,
  OneToMany,
  JoinColumn,
  ManyToOne,
  ManyToMany,
  JoinTable,
  Check,
  DeleteDateColumn,
} from 'typeorm';
import { Tag } from '../tag/tag.entity';
import { Model } from '../model/model.entity';
import { Part } from '../part/part.entity';
import { IsOptional } from 'class-validator';

@Entity()
export class InventoryItem {
  @PrimaryGeneratedColumn()
  id: number;

  @JoinColumn()
  @ManyToOne(() => Part, (part) => part.inventoryItems)
  part: Part;

  @JoinColumn()
  @ManyToOne(() => Model, (model) => model.inventoryItems)
  model: Model;

  @JoinColumn()
  @ManyToOne(() => Inventory, (inventory) => inventory.items)
  inventory: Inventory;

  @Column({ default: 0 })
  quantity: number;

  @Column({ default: 0 })
  @Check(`"publicCount" <= "quantity"`)
  publicCount: number;

  @DeleteDateColumn()
  archivedAt: Date;

  @IsOptional()
  @Column({ type: 'varchar', length: 500, nullable: true })
  notes?: string | null;

  @IsOptional()
  @Column({ type: 'jsonb', nullable: true })
  attributes?: object | null;

  @OneToMany(() => Listing, (listing) => listing.inventoryItem)
  listings: Listing[];

  @ManyToMany(() => Tag, (tag) => tag.inventoryItems)
  @JoinTable() // autogenerated name: "inventory_item_tags_tag"
  tags: Tag[];
}
