import { Inventory } from '../inventory/inventory.entity';
import { Listing } from '../listing/listing.entity';
import {
  Entity,
  Column,
  PrimaryGeneratedColumn,
  OneToMany,
  JoinColumn,
  ManyToOne,
  ManyToMany,
  JoinTable,
} from 'typeorm';
import { Tag } from '../tag/tag.entity';
import { Model } from '../model/model.entity';
import { Part } from '../part/part.entity';

@Entity()
export class InventoryItem {
  @PrimaryGeneratedColumn()
  id: number;

  @JoinColumn()
  @ManyToOne(() => Part, (part) => part.inventoryItems)
  part: Part;

  @JoinColumn()
  @ManyToOne(() => Model, (model) => model.inventoryItems)
  model: Model;

  @JoinColumn()
  @ManyToOne(() => Inventory, (inventory) => inventory.items)
  inventory: Inventory;

  @Column({ default: 0 })
  quantity: number;

  @Column({ default: 0 })
  publicCount: number;

  @Column({ type: 'varchar', length: 4000 })
  notes: string;

  // Change to jsonB
  @Column({ type: 'varchar', length: 4000 })
  attributes: string;

  @OneToMany(() => Listing, (listing) => listing.inventoryItem)
  listings: Listing[];

  @ManyToMany(() => Tag, (tag) => tag.inventoryItems)
  @JoinTable() // autogenerated name: "inventory_item_tags_tag"
  tags: Tag[];
}
