import {
  Column,
  Entity,
  JoinTable,
  ManyToMany,
  ManyToOne,
  OneToMany,
  PrimaryGeneratedColumn,
} from 'typeorm';
import { InventoryItem } from '../inventory-item/inventory-item.entity';
import { Part } from '../part/part.entity';

@Entity()
export class ModelType {
  @PrimaryGeneratedColumn()
  id: number;

  @Column({ type: 'varchar', length: 32 })
  name: string;

  @ManyToMany(() => Model, (model) => model.types)
  models: Model[];
}

@Entity()
export class Manufacturer {
  @PrimaryGeneratedColumn()
  id: number;

  @Column({ type: 'varchar', length: 32 })
  name: string;

  @ManyToMany(() => Model, (model) => model.types)
  models: Model[];
}

@Entity()
export class Model {
  @PrimaryGeneratedColumn()
  id: number;

  @ManyToOne(() => Manufacturer, (manufacturer) => manufacturer.models)
  manufacturer: Manufacturer;

  @Column({ type: 'varchar', length: 32 })
  name: string;

  @Column()
  year: number;

  @ManyToMany(() => ModelType, (type) => type.models)
  @JoinTable() // autogenerated name: model_types_model_type
  types: ModelType[];

  @OneToMany(() => InventoryItem, (item) => item.model)
  inventoryItems: InventoryItem[];

  @ManyToMany(() => Part, (part) => part.model)
  parts: Part[];
}
